version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: finance-ia-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8wkcadS6uRvt
      POSTGRES_DB: finance-ia
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    command: >
      sh -c "chmod -R 755 /var/lib/postgresql/data && docker-entrypoint.sh postgres"
volumes:
  .postgres-data:
